### PR TITLE
Mobile optimization

### LINKED ISSUE #5: Map interface is not mobile-friendly
Opening a Shelter popup in the map and navigating the data in the popup is pretty difficult on mobile. 

We should brainstorm ways to change the map's behaviour on mobile so that it can be used more easily.

### PR DESCRIPTION
**Pull request by AcharyaS97**

### CODE REVIEW

**Comment by zach-c-d** [comment]
Hey @AcharyaS97 , I'm having trouble getting this branch to build on my localhost. It seems there are changes in the application's stylesheets that create trouble with one of the project's dependancies: `uppy`. Tailwindcss postprocessor is unable to compile the service's stylesheets. This is the complaint I got on my end

```ruby
$ tailwindcss -i ./app/assets/stylesheets/application.css -o ./app/assets/builds/application.css --postcss --watch
$ node esbuild.config.js --watch
js     | ✘ [ERROR] Big integer literals are not available in the configured target environment ("chrome63", "edge79", "firefox67", "ios11.0", "safari11.1")
js     |
js     |     node_modules/@paralleldrive/cuid2/src/index.js:21:13:
js     |       21 │   let bits = 8n;
js     |          ╵              ~~
js     |
js     | ✘ [ERROR] Big integer literals are not available in the configured target environment ("chrome63", "edge79", "firefox67", "ios11.0", "safari11.1")
js     |
js     |     node_modules/@paralleldrive/cuid2/src/index.js:23:14:
js     |       23 │   let value = 0n;
js     |          ╵               ~~
js     |
js     | ✘ [ERROR] Transforming for-await loops to the configured target environment ("chrome63", "edge79", "firefox67", "ios11.0", "safari11.1") is not supported yet
js     |
js     |     node_modules/@uppy/utils/lib/getDroppedFiles/index.js:31:8:
js     |       31 │     for await (const file of webkitGetAsEntryApi(dataTransfer, logDropError)) {
js     |          ╵         ~~~~~
js     |
js     | ✘ [ERROR] Transforming async generator functions to the configured target environment ("chrome63", "edge79", "firefox67", "ios11.0", "safari11.1") is not supported yet
js     |
js     |     node_modules/@uppy/utils/lib/getDroppedFiles/utils/webkitGetAsEntryApi/index.js:20:4:
js     |       20 │     async *values() {
js     |          ╵     ~~~~~
js     |
js     | ✘ [ERROR] Transforming async generator functions to the configured target environment ("chrome63", "edge79", "firefox67", "ios11.0", "safari11.1") is not supported yet
js     |
js     |     node_modules/@uppy/utils/lib/getDroppedFiles/utils/webkitGetAsEntryApi/index.js:34:0:
js     |       34 │ async function* createPromiseToAddFileOrParseDirectory(entry, relativePath) {
js     |          ╵ ~~~~~
js     |
js     | ✘ [ERROR] Transforming for-await loops to the configured target environment ("chrome63", "edge79", "firefox67", "ios11.0", "safari11.1") is not supported yet
js     |
js     |     node_modules/@uppy/utils/lib/getDroppedFiles/utils/webkitGetAsEntryApi/index.js:44:8:
js     |       44 │     for await (const handle of entry.values()) {
js     |          ╵         ~~~~~
js     |
js     | ✘ [ERROR] Transforming async generator functions to the configured target environment ("chrome63", "edge79", "firefox67", "ios11.0", "safari11.1") is not supported yet
js     |
js     |     node_modules/@uppy/utils/lib/getDroppedFiles/utils/webkitGetAsEntryApi/index.js:50:0:
js     |       50 │ async function* getFilesFromDataTransfer(dataTransfer, logDropError) {
js     |          ╵ ~~~~~
js     |
error Command failed with exit code 1.
``` 

Does this css build error look familiar to you? Do you know how we might fix this?

**Comment by AcharyaS97** [comment]
I think this is ready to be merged in now if we're fine with how the map behaves on mobile in the latest commit.

 @zach-c-d We talked about this offline but i'll mention on here too for the sake of documenting. I haven't been able to reproduce the tailwind postprocessor issues on my end.

**Comment by zach-c-d** [comment]
I did some testing today of the latest changes and ran into some strange browser behaviour.

But visually it looks great in chrome! It appears to render perfectly at the bottom of the screen when a popup is clicked!

CADEE5E7-EEB6-41E0-8316-2C7803559DDB

I tested the map from my phone, and the popup appeared in the correct location! However I was unable to scroll down along further into the popup to get to the contact information section. 

Further, the bug where some of the popup doesn't render properly showed up. I suspect this an issue with Safari, and not with your code. A similar bug was seen in firefox until a few weeks ago. 

I found that I was unable to scroll through the popup in chrome and firefox on desktop as well (using the mobile screen dev tool).

Screenshot 2023-10-12 at 12 43 20 AM

I found a new UI bug in firefox on desktop as well. I'm not sure what's causing this, but it seems similar in nature to the previous bug where parts of the popup would become hidden behind blocks / un-render.

Screenshot 2023-10-11 at 11 24 06 PM

Screenshot 2023-10-11 at 11 24 13 PM

I also found that I was unable to close the popup after opening it on mobile. But this should be a straightforward fix by adding in a close button (was there in earlier commits)  perhaps.

**Comment by zach-c-d** [comment]
Whoops! Didn't mean to close this!!! That was a mis-click (smh)

**Comment by zach-c-d** [comment]
@AcharyaS97, do you see any of this behaviour on your end? Do you have an android phone you can test with? If yes, how does it render on the mobile browser you use?

I've scheduled a block of time for myself on Saturday to take a stab at sorting through some of the above bugs. In my opinion the approach would be to attack the issues with the following priority:

1) ensure the popup can be closed easily on ios safari, desktop firefox & chrome
2) take a quick look into if tailwind offers additional post-processing options to target specific browsers, as an attempt to fix these rendering issues in iOS safari and desktop firefox.

**Comment by AcharyaS97** [comment]
Thanks for the feedback @zach-c-d !!

> I tested the map from my phone, and the popup appeared in the correct location! However, I was unable to scroll down along further into the popup to get to the contact information section.

Yeah I'd noticed that when I was doing my testing as well. However, I did see that you can scroll, you just have to drag the scrollbar along the right side of the popup. I thought it was just an artifact of the fact that I was using a desktop browser with a mobile viewport. No worries, I'll fix that!

> I also found that I was unable to close the popup after opening it on mobile. But this should be a straightforward fix by adding in a close button (was there in earlier commits) perhaps.

Yeah, I'd meant to do this. I was thinking about it, and I just forgot to implement it. My thought was to use the shelter marker to toggle the visibility of the popup. In this vein, I was considering rendering an X or something on the selected marker to denote the one the user had selected. However, this is a bit harder to implement than initially thought because the marker has its own template.

> I found a new UI bug in firefox on desktop as well. I'm not sure what's causing this, but it seems similar in nature to the previous bug where parts of the popup would become hidden behind blocks / un-render.

Hmm, that's new. I hadn't seen that! I will add that on the todo as well.

> I've scheduled a block of time for myself on Saturday to take a stab at sorting through some of the above bugs.

Let me know what time, and I can hop on then as well!

**Comment by zach-c-d** [comment]
Just tested on my mobile phone and the scrolling works great now!!

**Pull request merged**
